function result = test_OFDF_strogatz_beta(graph_generating_algorithm, ddp, beta, options)
    if graph_generating_algorithm{1}{1} == "Watts Strogratz"
        params = num2cell([graph_generating_algorithm{1}{2}(1), graph_generating_algorithm{1}{2}(2), beta]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @watts_strogatz, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", options.fract_targ, ...
            "fraction_disturbances", options.fract_dist, ...
            "ddp", ddp, ...
            "old_results", options.old_results ...
            );
    end
