function result = test_strogatz_fraction_pws(graph_generating_algorithm, fraction, p_ws, options)
% TEST_STROGATZ_FRACTION_PWS
%   Description:
%       Tests for watts strogatz graphs for different p_ws and fractions
%   Output Arguments:
%       result     : set containing cost, runtime and trivial solutions.
%   Input Arguments:
%       graph_generating_algorithm : "Watts Strogratz"
%       fraction            : float, fraction of targets and disturbances
%       p_ws                : float, watts strogatz node degree
%       options             : size, sample_size, ddp, seed
    if graph_generating_algorithm{1}{1} == "Watts Strogratz"
        params = num2cell([options.size, 2, p_ws]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @watts_strogatz, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", fraction, ...
            "fraction_disturbances", fraction, ...
            "ddp", options.ddp, ...
            "seed", options.seed ...
            );
    end