function result = test_OFDF_scale_beta(graph_generating_algorithm, ddp, beta, options)
    if graph_generating_algorithm{1}{1} == "Scale Free"
        alpha = (1-beta)/2;
        gamma = 1-beta-alpha;
        params = num2cell([options.size, alpha, beta, gamma, 1, 1]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @sfg, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", options.fract_targ, ...
            "fraction_disturbances", options.fract_dist, ...
            "ddp", ddp, ...
            "old_results", options.old_results ...
            );
    end