function result = test_strogatz_size_beta(~, beta, size, options)
    params = num2cell([size, 2, beta]);
    [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
        @watts_strogatz, ...
        params, ...
        "sample_size", options.sample_size, ...
        "fraction_targets", options.fract_targ, ...
        "fraction_disturbances", options.fract_dist, ...
        "ddp", options.ddp ...
        );
