function result = test_strogatz_fraction_beta(graph_generating_algorithm, fraction, beta, options)
    if graph_generating_algorithm{1}{1} == "Watts Strogratz"
        params = num2cell([options.size, 2, beta]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @watts_strogatz, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", fraction, ...
            "fraction_disturbances", fraction, ...
            "ddp", options.ddp, ...
            "seed", options.seed ...
            );
    end