function result = test_strogatz_fraction_beta(~, beta, fraction, options)
    params = num2cell([options.size, 2, beta]);
    [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
        @watts_strogatz, ...
        params, ...
        "sample_size", options.sample_size, ...
        "fraction_targets", fraction, ...
        "fraction_disturbances", fraction, ...
        "ddp", options.ddp ...
        );
