function result = test_scale_size_beta(~, beta, size, options)
    alpha = (1-beta)/2;
    gamma = 1-beta-alpha;
    params = num2cell([size, alpha, beta, gamma, 1, 1]);
    [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
        @sfg, ...
        params, ...
        "sample_size", options.sample_size, ...
        "fraction_targets", options.fract_targ, ...
        "fraction_disturbances", options.fract_dist, ...
        "ddp", options.ddp ...
        );