function result = test_OFDF_node_degree(graph_generating_algorithm, ddp, node_degree, options)
% TEST_OFDF_NODE_DEGREE
%   Description:
%       Test for graphs with requested node degree. Includes a variable for
%       passing old results to calculate no interaction index (options.old_results).
%   Output Arguments:
%       result     : set containing cost, runtime and trivial solutions.
%   Input Arguments:
%       graph_generating_algorithm : "Erdos Renyi", "Watts Strogratz" or "Scale Free"
%       ddp        : ddp to be used ("output_feedback" or "dynamical_feedback")
%       node_degree: integer, requested average node degree
%       options    : size, sample_size, fract_targ, fract_dist, ddp, seed, old_results
    switch graph_generating_algorithm{1}{1}
        case "Erdos Renyi"
            graph_algorithm = @erdos_renyi_unconnected;
            params = num2cell([options.size, node_degree/(2*(options.size-1))]);
            [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
                graph_algorithm, ...
                params, ...
                "sample_size", options.sample_size, ...
                "fraction_targets", options.fract_targ, ...
                "fraction_disturbances", options.fract_dist, ...
                "ddp", ddp, ...
                "old_results", options.old_results, ...
                "seed", options.seed ...
                );
        case "Watts Strogratz"
            if iseven(node_degree)
                graph_algorithm = @watts_strogatz;
                params = num2cell([options.size, floor(node_degree/2), 0.2]);
                [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
                    graph_algorithm, ...
                    params, ...
                    "sample_size", options.sample_size, ...
                    "fraction_targets", options.fract_targ, ...
                    "fraction_disturbances", options.fract_dist, ...
                    "ddp", ddp, ...
                    "old_results", options.old_results, ...
                    "seed", options.seed ...
                    );
            else
                result.results_cost = 0;
                result.results_time = 0;
                result.results_trivial = 0;
            end
        case "Scale Free"
            beta = [0 0 0.44 0.62 0.72 0.78 0.83]; % for n = 50
            graph_algorithm = @sfg;
            alpha = (1-beta(node_degree))/2;
            gamma = (1-beta(node_degree))/2;
            delta_in = 10;
            delta_out = 10;
            params = num2cell([options.size, alpha, beta(node_degree), gamma, delta_in, delta_out]);
            [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
                graph_algorithm, ...
                params, ...
                "sample_size", options.sample_size, ...
                "fraction_targets", options.fract_targ, ...
                "fraction_disturbances", options.fract_dist, ...
                "ddp", ddp, ...
                "old_results", options.old_results, ...
                "seed", options.seed ...
                );
    end
end

function result = iseven(m)
    result = rem(m, 2) == 0;
end