function result = test_scale_fraction_beta(graph_generating_algorithm, fraction, beta, options)
% TEST_SCALE_FRACTION_BETA
%   Description:
%       Test for scale free graphs for different beta and fractions
%   Output Arguments:
%       result     : set containing cost, runtime and trivial solutions.
%   Input Arguments:
%       graph_generating_algorithm : "Scale Free"
%       fraction            : float, fraction of targets and disturbances
%       beta                : float, scale free parameter
%       options             : size, sample_size, ddp, seed
    if graph_generating_algorithm{1}{1} == "Scale Free"
        alpha = (1-beta)/2;
        gamma = 1-beta-alpha;
        params = num2cell([options.size, alpha, beta, gamma, 1, 1]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @sfg, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", fraction, ...
            "fraction_disturbances", fraction, ...
            "ddp", options.ddp, ...
            "seed", options.seed ...
            );
    end