function result = test_erdos_fraction_p(graph_generating_algorithm, fraction, p, options)
    if graph_generating_algorithm{1}{1} == "Erdos Renyi"
        params = num2cell([options.size, p]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @erdos_renyi, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", fraction, ...
            "fraction_disturbances", fraction, ...
            "ddp", options.ddp ...
            );
    end