function result = test_scale_fraction_alphagamma(~, alpha, fraction, options)
    gamma = 0.8-alpha;
    params = num2cell([options.size, alpha, 0.2, gamma, 1, 1]);
    [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
        @sfg, ...
        params, ...
        "sample_size", options.sample_size, ...
        "fraction_targets", fraction, ...
        "fraction_disturbances", fraction, ...
        "ddp", options.ddp ...
        );
