function result = test_node_degree(graph_generating_algorithm, ~, node_degree, options)
% TEST_NODE_DEGREE
%   Description:
%       Test for graphs with requested node degree.
%   Output Arguments:
%       result     : set containing cost, runtime and trivial solutions.
%   Input Arguments:
%       graph_generating_algorithm : "Erdos Renyi", "Watts Strogratz" or "Scale Free"
%       ~          : ignored input
%       node_degree: integer, requested average node degree
%       options    : size, sample_size, fract_targ, fract_dist, ddp, seed
    switch graph_generating_algorithm{1}{1}
        case "Erdos Renyi"
            graph_algorithm = @erdos_renyi_unconnected;
            params = num2cell([options.size, node_degree/(2*(options.size-1))]);
            [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
                graph_algorithm, ...
                params, ...
                "sample_size", options.sample_size, ...
                "fraction_targets", options.fract_targ, ...
                "fraction_disturbances", options.fract_dist, ...
                "ddp", options.ddp, ...
                "seed", options.seed ...
                );
        case "Watts Strogratz"
            if iseven(node_degree)
                graph_algorithm = @watts_strogatz;
                params = num2cell([options.size, floor(node_degree/2), options.default_p(3)]);
                [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
                    graph_algorithm, ...
                    params, ...
                    "sample_size", options.sample_size, ...
                    "fraction_targets", options.fract_targ, ...
                    "fraction_disturbances", options.fract_dist, ...
                    "ddp", options.ddp, ...
                    "seed", options.seed ...
                    );
            else
                result.results_cost = 0;
                result.results_time = 0;
                result.results_trivial = 0;
            end
        case "Scale Free"
            % tested values for alpha, beta & gamma that maps over to a scale free graph with average
            % k  = [1   2    3    4    5     6     7  ]
            beta = [0 0 0.4 0.58 0.68 0.75 0.79]; % for n = 100
            graph_algorithm = @sfg;
            alpha = (1-beta(node_degree))/2;
            gamma = (1-beta(node_degree))/2;
            delta_in = 10; % higher delta = higher average degree when beta is high (less effective for larger delta)
            delta_out = 10;
            params = num2cell([options.size, alpha, beta(node_degree), gamma, delta_in, delta_out]);
            [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
                graph_algorithm, ...
                params, ...
                "sample_size", options.sample_size, ...
                "fraction_targets", options.fract_targ, ...
                "fraction_disturbances", options.fract_dist, ...
                "ddp", options.ddp, ...
                "seed", options.seed ...
                );
    end
end

function result = iseven(m)
    result = rem(m, 2) == 0;
end