function result = test_strogatz_size_pws(graph_generating_algorithm, n, pws, options)
% TEST_STROGATZ_SIZE_PWS
%   Description:
%       Test for watts strogatz graphs for different p and sizes
%   Output Arguments:
%       result     : set containing cost, runtime and trivial solutions.
%   Input Arguments:
%       graph_generating_algorithm : "Watts Strogratz"
%       n                   : integer, graph size
%       p_ws                : float, watts strogatz node degree
%       options             : sample_size, fract_targ, fract_dist, ddp, seed
    if graph_generating_algorithm{1}{1} == "Watts Strogratz"
        params = num2cell([n, graph_generating_algorithm{1}{2}(2), pws]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @watts_strogatz, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", options.fract_targ, ...
            "fraction_disturbances", options.fract_dist, ...
            "ddp", options.ddp, ...
            "seed", options.seed ...
            );
    end
