function result = test_strogatz_size_beta(graph_generating_algorithm, size, beta, options)
    if graph_generating_algorithm{1}{1} == "Watts Strogratz"
        params = num2cell([size, 2, beta]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @watts_strogatz, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", options.fract_targ, ...
            "fraction_disturbances", options.fract_dist, ...
            "ddp", options.ddp ...
            );
    end
