function result = test_scale_fraction_beta(~, beta, fraction, options)
    alpha = (1-beta)/2;
    gamma = 1-beta-alpha;
    params = num2cell([options.size, alpha, beta, gamma, 1, 1]);
    [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
        @sfg, ...
        params, ...
        "sample_size", options.sample_size, ...
        "fraction_targets", fraction, ...
        "fraction_disturbances", fraction, ...
        "ddp", options.ddp ...
        );