function result = test_OFDF_scale_alphagamma(graph_generating_algorithm, ddp, alpha, options)
    if graph_generating_algorithm{1}{1} == "Scale Free"
        beta = 0;
        gamma = 1-alpha;
        params = num2cell([graph_generating_algorithm{1}{2}(1), alpha, beta, gamma, 1, 1]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @sfg, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", options.fract_targ, ...
            "fraction_disturbances", options.fract_dist, ...
            "ddp", ddp, ...
            "old_results", options.old_results, ...
            "seed", options.seed ...
            );
    end