function result = test_size(graph_generating_algorithm, ~, size, options)
    switch graph_generating_algorithm{1}{1}
        case "Erdos Renyi"
            graph_algorithm = @erdos_renyi;
        case "Watts Strogratz"
            graph_algorithm = @watts_strogatz;
        case "Scale Free"
            graph_algorithm = @sfg;
    end
    params = num2cell([size, graph_generating_algorithm{1}{2}(2:end)]);
    [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
        graph_algorithm, ...
        params, ...
        "sample_size", options.sample_size, ...
        "fraction_targets", options.fract_targ, ...
        "fraction_disturbances", options.fract_dist, ...
        "ddp", options.ddp ...
        );