function result = test_OFDF_scale_beta(graph_generating_algorithm, ddp, beta, options)
% TEST_OFDF_SCALE_BETA
%   Description:
%       Test for scale free graphs for different beta. Includes a variable for
%       passing old results to calculate no interaction index (options.old_results).
%   Output Arguments:
%       result     : set containing cost, runtime and trivial solutions.
%   Input Arguments:
%       graph_generating_algorithm : "Scale Free"
%       ddp                 : ddp to be used ("output_feedback" or "dynamical_feedback")
%       beta                : float, scale free parameter
%       options             : size, sample_size, fract_targ, fract_dist, ddp, seed, old_results
    if graph_generating_algorithm{1}{1} == "Scale Free"
        alpha = (1-beta)/2;
        gamma = 1-beta-alpha;
        params = num2cell([options.size, alpha, beta, gamma, 1, 1]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @sfg, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", options.fract_targ, ...
            "fraction_disturbances", options.fract_dist, ...
            "ddp", ddp, ...
            "old_results", options.old_results, ...
            "seed", options.seed ...
            );
    end