function result = test_scale_fraction_alphagamma(graph_generating_algorithm, fraction, alpha, options)
    if graph_generating_algorithm{1}{1} == "Scale Free"
        beta = 0;
        gamma = 1-alpha;
        params = num2cell([options.size, alpha, beta, gamma, 1, 1]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @sfg, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", fraction, ...
            "fraction_disturbances", fraction, ...
            "ddp", options.ddp, ...
            "seed", options.seed ...
            );
    end
