function result = test_different_fractions(graph_generating_algorithm, fract_dist, fract_targ, options)
    switch graph_generating_algorithm{1}{1}
        case "Erdos Renyi"
            graph_algorithm = @erdos_renyi;
        case "Watts Strogratz"
            graph_algorithm = @watts_strogatz;
        case "Scale Free"
            graph_algorithm = @sfg;
    end
    params = num2cell(graph_generating_algorithm{1}{2});
    [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
        graph_algorithm, ...
        params, ...
        "sample_size", options.sample_size, ...
        "fraction_targets", fract_targ, ...
        "fraction_disturbances", fract_dist, ...
        "ddp", options.ddp ...
        );