function result = test_OFDF_erdos_p(graph_generating_algorithm, ddp, p, options)
    if graph_generating_algorithm{1}{1} == "Erdos Renyi"
        params = num2cell([options.size, p]);
        [result.results_cost, result.results_time, result.results_trivial] = run_test( ...
            @erdos_renyi, ...
            params, ...
            "sample_size", options.sample_size, ...
            "fraction_targets", options.fract_targ, ...
            "fraction_disturbances", options.fract_dist, ...
            "ddp", ddp, ...
            "old_results", options.old_results, ...
            "seed", options.seed ...
            );
    end